; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lsx  < %s | FileCheck %s

define <2 x i64> @not_v2i64(<2 x i64> %a) {
; CHECK-LABEL: not_v2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <2 x i64> %a, <i64 -1, i64 -1>
  ret <2 x i64> %not
}

define <4 x i32> @not_v4i32(<4 x i32> %a) {
; CHECK-LABEL: not_v4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <4 x i32> %a, <i32 -1, i32 -1, i32 -1, i32 -1>
  ret <4 x i32> %not
}

define <8 x i16> @not_v8i16(<8 x i16> %a) {
; CHECK-LABEL: not_v8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <8 x i16> %a, <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>
  ret <8 x i16> %not
}

define <16 x i8> @not_v16i8(<16 x i8> %a) {
; CHECK-LABEL: not_v16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vxori.b $vr0, $vr0, 255
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <16 x i8> %a, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  ret <16 x i8> %not
}


define <2 x i64> @andn_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: andn_v2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vandn.v $vr0, $vr1, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <2 x i64> %b, <i64 -1, i64 -1>
  %and = and <2 x i64> %not, %a
  ret <2 x i64> %and
}

define <4 x i32> @andn_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: andn_v4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vandn.v $vr0, $vr1, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <4 x i32> %b, <i32 -1, i32 -1, i32 -1, i32 -1>
  %and = and <4 x i32> %not, %a
  ret <4 x i32> %and
}

define <8 x i16> @andn_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: andn_v8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vandn.v $vr0, $vr1, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <8 x i16> %b, <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>
  %and = and <8 x i16> %not, %a
  ret <8 x i16> %and
}

define <16 x i8> @andn_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: andn_v16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vandn.v $vr0, $vr1, $vr0
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <16 x i8> %b, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %and = and <16 x i8> %not, %a
  ret <16 x i8> %and
}


define <2 x i64> @orn_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: orn_v2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vorn.v $vr0, $vr0, $vr1
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <2 x i64> %b, <i64 -1, i64 -1>
  %or = or <2 x i64> %not, %a
  ret <2 x i64> %or
}

define <4 x i32> @orn_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: orn_v4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vorn.v $vr0, $vr0, $vr1
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <4 x i32> %b, <i32 -1, i32 -1, i32 -1, i32 -1>
  %or = or <4 x i32> %not, %a
  ret <4 x i32> %or
}

define <8 x i16> @orn_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: orn_v8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vorn.v $vr0, $vr0, $vr1
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <8 x i16> %b, <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>
  %or = or <8 x i16> %not, %a
  ret <8 x i16> %or
}

define <16 x i8> @orn_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: orn_v16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vorn.v $vr0, $vr0, $vr1
; CHECK-NEXT:    jr $ra
entry:
  %not = xor <16 x i8> %b, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %or = or <16 x i8> %not, %a
  ret <16 x i8> %or
}
