; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <8 x i32> @test_masked_8xi32_perm(<8 x i32> %vec) {
; CHECK-LABEL: test_masked_8xi32_perm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    la.pcrel	$r4, .LCPI0_0
; CHECK-NEXT:    # la expanded slot
; CHECK-NEXT:    xvld	$xr1, $r4, 0
; CHECK-NEXT:    xvperm.w	$xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
entry:
  %shuf = shufflevector <8 x i32> %vec, <8 x i32> undef, <8 x i32> <i32 4, i32 2, i32 0, i32 6, i32 7, i32 2, i32 3, i32 6>
  ret <8 x i32> %shuf
}

define <8 x float> @test_masked_8xfloat_perm(<8 x float> %vec) {
; CHECK-LABEL: test_masked_8xfloat_perm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    la.pcrel	$r4, .LCPI1_0
; CHECK-NEXT:    # la expanded slot
; CHECK-NEXT:    xvld	$xr1, $r4, 0
; CHECK-NEXT:    xvperm.w	$xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
entry:
  %shuf = shufflevector <8 x float> %vec, <8 x float> undef, <8 x i32> <i32 4, i32 2, i32 0, i32 6, i32 7, i32 2, i32 3, i32 6>
  ret <8 x float> %shuf
}