; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s


define <4 x i64> @perm_cl_int_4x64(<4 x i64> %A) nounwind readnone {
; CHECK-LABEL: perm_cl_int_4x64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpermi.d	$xr0, $xr0, 108
; CHECK-NEXT:    jr $ra
entry:
  %B = shufflevector <4 x i64> %A, <4 x i64> undef, <4 x i32> <i32 0, i32 3, i32 2, i32 1>
  ret <4 x i64> %B
}
define <4 x double> @perm_cl_fp_4x64(<4 x double> %A) nounwind readnone {
; CHECK-LABEL: perm_cl_fp_4x64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpermi.d	$xr0, $xr0, 108
; CHECK-NEXT:    jr $ra
entry:
  %B = shufflevector <4 x double> %A, <4 x double> undef, <4 x i32> <i32 0, i32 3, i32 2, i32 1>
  ret <4 x double> %B
}