; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s
define <8 x i32> @add_od_ev_int(<8 x i32> %x) {
; CHECK-LABEL: add_od_ev_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvpickod.w	$xr1, $xr0, $xr0
; CHECK-NEXT:    xvpickev.w	$xr0, $xr0, $xr0
; CHECK-NEXT:    xvadd.w	$xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
entry:
  %a = shufflevector <8 x i32> %x, <8 x i32> undef, <8 x i32> <i32 undef, i32 2, i32 8, i32 10, i32 4, i32 6, i32 undef, i32 14>
  %b = shufflevector <8 x i32> %x, <8 x i32> undef, <8 x i32> <i32 1, i32 3, i32 9, i32 undef, i32 5, i32 7, i32 13, i32 15>
  %r = add <8 x i32> %a, %b
  ret <8 x i32> %r
}

define <8 x float> @add_od_ev_fp(<8 x float> %x) {
; CHECK-LABEL: add_od_ev_fp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvpickod.w	$xr1, $xr0, $xr0
; CHECK-NEXT:    xvpickev.w	$xr0, $xr0, $xr0
; CHECK-NEXT:    xvfadd.s	$xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
entry:
  %a = shufflevector <8 x float> %x, <8 x float> undef, <8 x i32> <i32 undef, i32 2, i32 8, i32 10, i32 4, i32 6, i32 undef, i32 14>
  %b = shufflevector <8 x float> %x, <8 x float> undef, <8 x i32> <i32 1, i32 3, i32 9, i32 undef, i32 5, i32 7, i32 13, i32 15>
  %r = fadd <8 x float> %a, %b
  ret <8 x float> %r
}