; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <8 x i32> @xshf_int(<8 x i32> %x) {
; CHECK-LABEL: xshf_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvshuf4i.w	$xr0, $xr0, 27
; CHECK-NEXT:    xvadd.w	$xr0, $xr0, $xr0
; CHECK-NEXT:    jr $ra
entry:
  %a = shufflevector <8 x i32> %x, <8 x i32> undef, <8 x i32> <i32 3, i32 2, i32 1, i32 0, i32 7, i32 6, i32 5, i32 4>
  %b = shufflevector <8 x i32> %x, <8 x i32> undef, <8 x i32> <i32 3, i32 2, i32 1, i32 0, i32 7, i32 6, i32 5, i32 4>
  %r = add <8 x i32> %a, %b
  ret <8 x i32> %r
}

define <8 x float> @xshf_fp(<8 x float> %x) {
; CHECK-LABEL: xshf_fp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvshuf4i.w	$xr0, $xr0, 27
; CHECK-NEXT:    xvfadd.s	$xr0, $xr0, $xr0
; CHECK-NEXT:    jr $ra
entry:
  %a = shufflevector <8 x float> %x, <8 x float> undef, <8 x i32> <i32 3, i32 2, i32 1, i32 0, i32 7, i32 6, i32 5, i32 4>
  %b = shufflevector <8 x float> %x, <8 x float> undef, <8 x i32> <i32 3, i32 2, i32 1, i32 0, i32 7, i32 6, i32 5, i32 4>
  %r = fadd <8 x float> %a, %b
  ret <8 x float> %r
}